### ISSUE TITLE
Extension doesn't pick up action

### ISSUE THREAD

**Issue by kian99** [babakks/vscode-juju-charmcraft-ide#13] opened 2023-10-12 09:06 UTC
I think I'm seeing an unexpected error from the extension. It's reporting an "undefinedEvent" for an action.
The offending line is the following:
```
        # create-authorization-model action
        self.framework.observe(
            self.on.create_authorization_model_action,
            self._on_create_authorization_model_action,
        )
```
![Screenshot from 2023-10-12 11-04-16](https://github.com/babakks/vscode-juju-charmcraft-ide/assets/46668016/276c613c-84f1-4f48-a062-da35381cb463)

![Screenshot from 2023-10-12 11-04-35](https://github.com/babakks/vscode-juju-charmcraft-ide/assets/46668016/956c6466-51eb-4516-b568-7cd5ffe06c0e)

Inside actions.yaml 
```
create-authorization-model:
  description: |
    Creates the authorization model using the content of the
    specified file and returns the authorization model ID.
  params:
    model:
      type: string
      description: |
        The JSON string containing the authorization model.
  required: [model]
```

**Comment by babakks** [comment] 2023-10-12 09:16
Thanks for reporting this @kian99. Could you please confirm the error shows when there's no line break (i.e., when the entire `framework.observe` call is in a single line)?

**Comment by kian99** [comment] 2023-10-12 10:38
Yes, the issue remains even with everything on the same line

**Comment by babakks** [comment] 2023-11-23 15:21
The cause of this bug is still unknown. I'll close it for now, but will reopen when we had more clues.

**Closed** 2023-11-23 15:21 UTC
Labels: bug

**Comment by Romek-cloud** [comment] 2024-08-03 19:12
Path
